### ISSUE TITLE
markdown-template failing for us since generator-react-sdk:0.1.5 was released

### ISSUE THREAD

**Issue by bjoernmartin** [asyncapi/generator-react-sdk#29]
For a few hours our Markdown documentation generation fails. Since it indicates this module as the cause and fetches the version just released I thought this is the cause rather than something with `markdown-template`. Generation worked fine before that.

Here's the output (project references anonymized - I hope):

```bash
$ npm run asyncapi-md

> @project@0.0.1 asyncapi-md /home/martin/project
> ag ./docs/asyncapi.yaml @asyncapi/markdown-template --param outFilename=events.md --output ./docs/ --force-write

npm http fetch GET 304 ...
...

+ @asyncapi/markdown-template@0.11.1
added 162 packages from 85 contributors, removed 168 packages and moved 2 packages in 10.37s

11 packages are looking for funding
  run `npm fund` for details

Something went wrong:
Error: Cannot find module '/home/martin/project/node_modules/@asyncapi/generator/node_modules/@asyncapi/markdown-template/node_modules/@asyncapi/generator-react-sdk/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:295:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:508:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/martin/project/node_modules/@asyncapi/generator/node_modules/@asyncapi/markdown-template/__transpiled/asyncapi.js:5:25)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/martin/project/node_modules/@asyncapi/generator-react-sdk/src/renderer/template.ts:45:25
    at new Promise (<anonymous>)
    at importComponent (/home/martin/project/node_modules/@asyncapi/generator-react-sdk/src/renderer/template.ts:38:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @project@0.0.1 asyncapi-md: `ag ./docs/asyncapi.yaml @asyncapi/markdown-template --param outFilename=events.md --output ./docs/ --force-write`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @project@0.0.1 asyncapi-md script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/martin/.npm/_logs/2021-02-05T14_16_38_557Z-debug.log
```
I also attached the (also anonymized) [2021-02-05T14_16_38_557Z-debug.log](https://github.com/asyncapi/generator-react-sdk/files/5933389/2021-02-05T14_16_38_557Z-debug.log).

Providing a full project would take a bit longer. Just let me know if this doesn't show up for you at all and I'll dig into that.

Thanks for any pointers! Or a fix :)

**Comment by derberg** [comment]
Thanks @bjoernmartin 
Let us track progress in this first issue that was created few minutes ago https://github.com/asyncapi/generator/issues/498
